language: java


addons:
  sonarcloud:
    organization: "mirkobaffo"
    token:
      secure: "FZ8K6wd0O4zfDJa8GbYSQ7D5o6Ogd/8aOYB094s/qHu8kRa8j8Wai4A5B1GCAyICu9/sBqz2wN/cCARnhqk9R9AT5Fqjw2AukXzQ8GmL92mvCJP75+SvXFdqxFad0guzND5NRaClaTvu2oETm7XngNPBwgwYUuT+dkBiK/WlshSAUIh01MSXaaA42MqxYG8JAJ2ndMUGFVNx27nKve5GFCJWl9+vjm0uxDL+RWx2JGIIP0i/lWh31Yi3R5ghwg5eMvhpqnCBPOs/nRmjTBhgC4VdZDqWvs5tbLZjtB3qVEyp6s4SYYG2pepINZk2jL8NTTh7Wv9l4N5r1lrcxgoScbdojSq9GjZJ1TNj9sKhUZZP4TT38ASKtDOMsmkQHiglVgm9sfS43s0u+iPn85OhcG2Ida/wNfVxmwrE0G/KQ9Onvhl5yXExezEXZ0Gdih3Jjo0O7siTMPQXeHsp4ERURFcqiEg9LTTunsgO0K9WLr8z4qWWYqlukS1fiS0HGt2omn09W0VIJLb3Qks4+9FNUqQQxxSr6IafDaEGF/KSzwom/MWyp4ZM1Sm4y4oYhsEi1nLSUXJABWOX7ImZcYFgjZMF6aAlNbxH0Emf+vaZp9v0rQYhJ/nhpvtA/yXWqsORVe8o9WV6hZkjC5euTrLc5jFfubh/yKXvGEQJmpYet8I="+hVUEaZNVg+AeDbTGd5RvXirRTBoH30M44sUjXkbHzxZCEs6ELOYcooamjD5dxFF2vKAuSDj+DLVl2QCsUvlexBbLKRCYhVrnKQ9iE9lZp/TA08wZPQgE1O3zXGmkIlFTnMuvmagcKALhh6yyTCDP14cNERwn9Nr/m7UM55Rz184ZXBh3P3GVvSRl6Z+2/ycfTcmVyfGvgKBXZQ/DGgexoQxL1rVCpWrOLI/X2OUNQRITRoN3aIdo9C7D8kcgOfp+2XH5NvlcXKzS8zA1YDHKueo/TSpujH8X2YnwuQIyephkntLhm8tZWrorJiKZ5NnmKHYMHWF91Bosobuh5uRoZQAm59eVY97+sDq8u75XuE+cf9CXQ09k0/FCjN43K+S688iydzH+hDOarfH7Kp0dXYWVoGiCBPIpygjVYtEu2keCyJrtNi8jssEUrP9/jnLc3fjwOcPgzsgqhN8AdClHNkeA7oJkS8pKCgr52HvcQv6vZuVIVS9mZh3/X5HZe4/BrvUOFJBG+ZfDXrUrBNGEkNYFZruZy9Q/YOKaAy1R+8D0Q4P9qzbo8IMg1LxOwvbm8+BB8SIKNwql7Ug=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=mirkobaffo_My_Avro

